from get_db_table_information import GetDbTableInformationClass
import bitwise_public
test_table_class = GetDbTableInformationClass(bitwise_public.HTTPMethod.POST)
test_table_class.get_db_name_length(bitwise_public.HTTPMethod.POST)
test_table_class.get_db_name(bitwise_public.HTTPMethod.POST)
